/**
 * This module contain all constants to be
 * used commonly along the whole app
 */
var AppConstants = {
  CHANGE_EVENT: 'CHANGE_EVENT',
  RECEIVE_ARTICLES: 'RECEIVE_ARTICLES',
  RECEIVE_ARTICLES_ERROR: 'RECEIVE_ARTICLES_ERROR',
  RECEIVE_BOOKS: 'RECEIVE_BOOKS',
  RECEIVE_BOOKS_ERROR: 'RECEIVE_BOOKS_ERROR',
  RECEIVE_REVIEWS: 'RECEIVE_REVIEWS',
  RECEIVE_REVIEWS_ERROR: 'RECEIVE_REVIEWS_ERROR',
  RECEIVE_STORIES: 'RECEIVE_STORIES',
  RECEIVE_STORIES_ERROR: 'RECEIVE_STORIES_ERROR'
};

module.exports = AppConstants;
