var AppConstants = {
  CHANGE_EVENT: 'CHANGE_EVENT',
  RECEIVE_ARTICLES: 'RECEIVE_ARTICLES',
  RECEIVE_ARTICLES_ERROR: 'RECEIVE_ARTICLES_ERROR',
  RECEIVE_BOOKS: 'RECEIVE_BOOKS',
  RECEIVE_BOOKS_ERROR: 'RECEIVE_BOOKS_ERROR'
};

module.exports = AppConstants;
