var AppConstants = {
  CHANGE_EVENT: 'CHANGE_EVENT',
  RECIEVE_ARTICLES: 'RECIEVE_ARTICLES',
  RECIEVE_ARTICLES_ERROR: 'RECIEVE_ARTICLES_ERROR',
  RECIEVE_BOOKS: 'RECIEVE_BOOKS',
  RECIEVE_BOOKS_ERROR: 'RECIEVE_BOOKS_ERROR'
};

module.exports = AppConstants;
